"use client"

import Head from "next/head"
import Button from "@mui/material/Button"
import { RiPlantFill } from "react-icons/ri/"

import React from "react"

export default function Home() {
  return (
    <>
      <Head>
        <title>CSF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="-mt-40">
        <div
          className="pt-32 bg-cover bg-center px-5 lg:px-0 bg-black"
          //style={{ backgroundImage: `url("/images/test1.png")` }}
        >
          <div className="flex mx-auto items-center border-b-8 border-black">
            <div className="flex flex-col md:flex-row w-full items-center justify-between text-white pt-16 md:pt-48 pb-10 px-4 md:px-10 md:pb-28 lg:pb-40 gap-10 md:gap-0">
              <h1 className=" text-2xl md:text-4xl font-light text-left mb-4 pt-0 md:w-1/2">
                The{" "}
                <span className="font-bold">
                  Deforestation Impacts Calculator
                </span>{" "}
                is a tool to assess the social and environmental damage caused
                by forest logging in the Amazon
              </h1>
              <div className="flex mx-auto gap-8">
                <Button
                  className="bg-green-400 hover:bg-green-100 py-4 px-8 text-green-900 font-bold"
                  variant="contained"
                  color="primary"
                  size="large"
                  href="/"
                  target="_blank"
                >
                  CALCULATOR
                </Button>
                <Button
                  className="bg-green-400 hover:bg-green-100 py-4 px-8 text-green-900 font-bold"
                  variant="contained"
                  color="primary"
                  size="large"
                  href="/"
                  target="_blank"
                >
                  GUIA DE USO
                </Button>
              </div>
            </div>
          </div>
        </div>

        <h1 className="flex text-2xl md:text-4xl font-bold p-10 border-b-8 border-black gap-4 items-center">
          <RiPlantFill />
          Como funciona
        </h1>

        <div className="flex flex-col md:flex-row mx-0 md:mx-auto pt-0 justify-between items-center gap-10 md:gap-0">
          <div className="w-full md:w-1/2 p-10 md:border-r-8 border-black">
            <div className="mb-4 text-xl">
              <p>
                Você pode incluir algumas informações sobre o contexto para que
                a calculadora estime o valor dos impactos de forma mais precisa.
                <br />A localização define outras variáveis como:
              </p>
              <div className="mt-4">
                <ul>
                  <li>- Densidade e tamanho da população afetada</li>

                  <li>- Média de consumo de peixe</li>

                  <li>- Custo de transporte para recuperação de áreas</li>

                  <li>- Tipo de garimpo</li>
                </ul>
              </div>

              <p className="mt-4">
                Caso não tenha informações específicas, não tem problema, serão
                incluídos automaticamente valores médios de contexto e impacto e
                resultados e suas explicações serão gerados na sequencia.
              </p>
            </div>
          </div>

          <div
            className="bg-cover bg-center w-full md:w-1/2 h-[408px] border border-black bg-black"
            //style={{ backgroundImage: `url("/images/teste2.png")` }}
          >
            video
          </div>
        </div>

        <h1 className="flex text-2xl md:text-4xl font-bold p-10 border-t-8 border-black gap-4 items-center">
          <RiPlantFill /> Entenda os impactos do desmatamento
        </h1>

        <div className="mt-0 pt-0 pb-0 px-4 md:px-0 border-y-8 border-black">
          <div className="mx-auto p-0">
            <div className="flex flex-col md:flex-row justify-between p-0 gap-0">
              <div className="flex flex-col justify-between bg-white border-b-4 md:border-b-0 p-0 gap-4 shadow-none md:w-1/2 md:border-r-8 border-black">
                <div>
                  <img className="w-16 mx-auto pt-8" src="/images/ico1.svg" />
                  <div className="w-1/2 md:w-2/3 mx-auto text-2xl md:text-3xl font-bold mt-0 border-b-2 border-black px-4 py-4 text-center">
                    Restauração
                  </div>
                </div>
                <div className="text-center px-6 md:w-2/3 mx-auto text-2xl">
                  Áreas são abertas para escavação e para a construção de
                  infraestrutura, como estradas e pistas de pouso
                </div>
                <div className="p-10 text-center w-full">
                  <Button
                    className="shadow-sm font-bold w-full md:w-1/4 py-4 px-4 text-green-800 border-green-400 hover:border-green-400 bg-green-400 hover:bg-green-500"
                    variant="outlined"
                    color="primary"
                    size="medium"
                    href="/"
                    target="_blank"
                  >
                    Leia mais
                  </Button>
                </div>
              </div>

              <div className="flex flex-col justify-between bg-white border-0 p-0 gap-4 shadow-none md:w-1/2 border-r-0 border-black">
                <div>
                  <img className="w-16 mx-auto pt-8" src="/images/ico2.svg" />
                  <div className="w-1/2 md:w-2/3 mx-auto text-2xl md:text-3xl font-bold mt-0 border-b-2 border-black px-4 py-4 text-center">
                    Serviços Ecossistêmicos
                  </div>
                </div>
                <div className="text-center px-6 md:w-2/3 mx-auto text-2xl">
                  Áreas são abertas para escavação e para a construção de
                  infraestrutura, como estradas e pistas de pouso
                </div>
                <div className="p-10 text-center w-full">
                  <Button
                    className="shadow-sm font-bold w-full md:w-1/4 py-4 px-4 text-green-800 border-green-400 hover:border-green-400 bg-green-400 hover:bg-green-500"
                    variant="outlined"
                    color="primary"
                    size="medium"
                    href="/"
                    target="_blank"
                  >
                    Leia mais
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
